version: '3.9'

services:
  ubuntu_node:
    image: ubuntu_gcc
    container_name: ubuntu_gcc
    ports:
      - "9001:9001"
    build:
      context: .
      dockerfile: Dockerfile
   
    stdin_open: true
    tty: true
