version: '3.8'

services:
  ubuntu_ssh:
    image: ubuntu
    container_name: telua
    ports:
      - "2883:1883"
      - "9001:9001"
    build:
      context: .
      dockerfile: Dockerfile
   
    stdin_open: true
    tty: true
