version: '3.9'

services:
  ubuntu_node:
    image: ubuntu_grafana
    container_name: ubuntu_grafana
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Grafana access: host 3000 -> container 3000 
    stdin_open: true
    tty: true
     
