#include <jni.h>
#include <string>
#include "Main.h" // Header file generated by javac -h command
#include "Greeting.h"

extern "C" {
    // Function name must follow rule: Java_ClassName_MethodName
    JNIEXPORT jstring JNICALL Java_Main_getGreetingFromCpp(JNIEnv *env, jobject obj) {
        Greeting greeting;
        std::string hello = greeting.getMessage();
        // Convert std::string to jstring (Java String type)
        return env->NewStringUTF(hello.c_str());
    }
}