name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
 
      - name: Build the Docker image
        run: |
          docker build -t kanban-board:latest -f ubuntu-kanban_board/Dockerfile ubuntu-kanban_board

      - name: Run container
        run: |
          docker run -d --name kanban_temp kanban-board:latest
      
      - name: Copy index.html from container
        run: |
          mkdir -p ubuntu-kanban_board/dist
          docker cp kanban_temp:/app/dist/index.html ubuntu-kanban_board/dist/index.html
      
      - name: Run unit tests
        run: docker exec kanban_temp python /app/src/unittest/test_app.py

      - name: Copy test reports from container
        if: always()
        run: docker cp kanban_temp:/app/test-reports ./test-reports || true

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unittest-results
          path: test-reports/

      - name: Stop and remove container
        if: always()
        run: |
          docker rm -f kanban_temp

      - name: Upload index.html as artifact
        uses: actions/upload-artifact@v4
        with:
          name: index-html
          path: ubuntu-kanban_board/dist/index.html
